export const IS_LOGIN = 'IS_LOGIN';
export const LOGOUT = 'LOGOUT';
export const USER_DETAILS = 'USER_DETAILS';

export const GETAllCATEGORY = 'GETAllCATEGORY';
export const SELECTEDADDRESS = 'SELECTEDADDRESS';
export const GETALLADDRESS = 'GETALLADDRESS';
export const GETALLRESTAURANTS = 'GETALLRESTAURANTS';
//GetAllExternalRestaurant
export const GETALLEXTERNALRESTAURANT = 'GETALLEXTERNALRESTAURANT';

export const GETALLRISTORANTI = 'GETALLRISTORANTI';
export const GETRESTAURANTDETAILS = 'GETRESTAURANTDETAILS';
export const LOADINGRESTORANTI = 'LOADINGRESTORANTI';

// cart actions
export const ADDTOCART = 'ADDTOCART';
